### ISSUE TITLE
一些增强和优化建议

### ISSUE THREAD

**Issue by erbanku** [hahahumble/speechgpt#1]
**功能增强：**
目前的状况总体上相当不错，但我希望能增加一些实用的功能，例如：

- 自动识别语音输入的语言，并在用户停顿指定时长后将识别结果自动发送给GPT；
- 在朗读功能中，不要忽略任何语言，而是在多语言环境中进行全面朗读，而不是跳过未在设置中指定的语言；
- 在每个对话旁边增加一个“重新朗读”的按钮（如果能同时暂停和停止就更好了）；
- 支持PWA。

**需要改进：**
此外，语音输出功能的稳定性有待提高，有时候无法正常输出。

以上是我个人的一些建议，希望你能予以考虑，谢谢！

**Comment by hahahumble** [comment]
非常感谢你的反馈。其中这三点我也有考虑过，并计划在之后的更新中增加：
- 自动识别用户语音输入的语言，当用户停顿一定时长后，将识别结果自动发送给 GPT；
- 在每个对话旁边添加一个 “朗读” 按钮；
- 支持 PWA。

关于你提到的多语言环境问题，是指对话里的多语言还是整个聊天中的多语言？

- 对于对话中的多语言，这取决于语音合成 API 是否支持多种语言；
- 对于整个聊天环境中的多语言，需要先检测对话中的语言，然后进行语音合成。之后的更新中我会考虑添加一个选项，让用户可以为每种语言选择默认的语音，再增加自动识别语言的选项。

由于我预期的 SpeechGPT 主要用法是用户直接访问官网，因此目前所有配置信息都存储在浏览器中，并可通过设置进行修改。当然，之后更新也会提供通过环境变量来初始化默认配置的方法。

**Comment by erbanku** [comment]
多语言环境问题主要是针对单次回复朗读，因为发现朗读GPT回复时，TTS（Azure TTS）会自动跳过非在设置里指定语言，想要的效果时足够自然地处理这一场景，而非忽略。

谢谢你的回复。

**Comment by hahahumble** [comment]
目前大多数语音合成 API 都只支持单一语言的朗读，而手动将其拆分为多种语言又容易出错。因此，可能要等基础功能完善后才考虑这个功能。

**Comment by xingfanxia** [comment]
> Author

很需要通过env来设置这些key

**Comment by hahahumble** [comment]
> > 对了，还有一个更为重要的建议： 支持在部署时，通过环境变量（Environment Variable）来设置页面中需要手动设置的密钥和其他参数变量。 尽管可以直接将这些变量放入代码中，但在前端存储这些信息可能并不是一个好主意。
> 
> +1, 很需要通过 env 来设置这些 key @hahahumble

用 env 来设置这些 key 之后，在发送的请求里也可以看见这些 key，还需要加一层 Api 中间件吗？

**Comment by chengfengfengwang** [comment]
可以自动语音识别吗？就是说中文识别成中文，说英语识别成英语

**Comment by hahahumble** [comment]
Azure 语音识别语言设为中文，是可以同时识别中文和英文的，之后也会支持可以同时识别中英文的语音识别 API

**Comment by chengfengfengwang** [comment]
我在跟ai对话的时候，会担心自己的英语有语法错误，能否自动预设promt让ai纠错？

**Comment by hahahumble** [comment]
> 我在跟 ai 对话的时候，会担心自己的英语有语法错误，能否自动预设 promt 让 ai 纠错？

可以通过写类似这样的 Prompt 实现：Please correct my grammar first, and then answer my question while practicing English speaking with me

**Comment by chengfengfengwang** [comment]
> > 我在跟 ai 对话的时候，会担心自己的英语有语法错误，能否自动预设 promt 让 ai 纠错？
> 
> 可以通过写类似这样的 Prompt 实现：Please correct my grammar first, and then answer my question while practicing English speaking with me

谢谢，很有用的prompt

**Comment by onion0835** [comment]
能否增加一个代理 url 设置，使得调用走代理

**Comment by hahahumble** [comment]
> 能否增加一个代理 url 设置，使得调用走代理

今晚可以更新

**Comment by TomBener** [comment]
> 用 env 来设置这些 key 之后，在发送的请求里也可以看见这些 key，还需要加一层 Api 中间件吗？

或许可以参考一下这个项目：https://github.com/ddiu8081/chatgpt-demo

**Comment by fangdajiang** [comment]
> https://github.com/ddiu8081/chatgpt-demo

env 设置好以后，就和前端无关了。

可参考 https://github.com/Yidadaa/ChatGPT-Next-Web 里面的 openai key 和 code 机制很好地解决了既可以依赖后端 env 内置，也可以前端自行设置覆盖 key，并用 code 控制访问。

**Comment by dfkj321** [comment]
经常读了50个词后，就开始停止读了，请问可以在哪里修改这个读词限制呢

**Comment by laikedou** [comment]
> 非常感谢你的反馈。其中这三点我也有考虑过，并计划在之后的更新中增加：
> 
> * 自动识别用户语音输入的语言，当用户停顿一定时长后，将识别结果自动发送给 GPT；
> * 在每个对话旁边添加一个 “朗读” 按钮；
> * 支持 PWA。
> 
> 关于你提到的多语言环境问题，是指对话里的多语言还是整个聊天中的多语言？
> 
> * 对于对话中的多语言，这取决于语音合成 API 是否支持多种语言；
> * 对于整个聊天环境中的多语言，需要先检测对话中的语言，然后进行语音合成。之后的更新中我会考虑添加一个选项，让用户可以为每种语言选择默认的语音，再增加自动识别语言的选项。
> 
> 由于我预期的 SpeechGPT 主要用法是用户直接访问官网，因此目前所有配置信息都存储在浏览器中，并可通过设置进行修改。当然，之后更新也会提供通过环境变量来初始化默认配置的方法。

建议新增下载语音的功能！非常有用
