### ISSUE TITLE
error

### ISSUE THREAD

**Issue by freer123** [hahahumble/speechgpt#11]
### Describe the bug

openai key和azure key都是验证过没问题的，但是每次输入后反馈都是there was an error with your request

### Steps to reproduce

1.使用chrome浏览器打开speechgpt.app
2.输入openai key和azure key
3。输入文字或语音
4。浏览器弹窗反馈there was an error with your request

**Comment by erbanku** [comment]
请确保 `Azure Region`和`需要朗读的语言`配置正确

**Comment by hahahumble** [comment]
还要确保网络环境能正常连接 `api.openai.com`

**Comment by freer123** [comment]
配置改为system反馈也一样，连接api.openai.com反馈如下，似乎是这个网络环境问题。

{
  "error": {
    "message": "Invalid URL (GET /)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

**Comment by erbanku** [comment]
> 配置改为system反馈也一样，连接api.openai.com反馈如下，似乎是这个网络环境问题。
> 
> { "error": { "message": "Invalid URL (GET /)", "type": "invalid_request_error", "param": null, "code": null } }

可以先开全局试试？排除一下问题

**Comment by freer123** [comment]
开了全局还是报错

**Comment by hahahumble** [comment]
可以再验证一下 `OpenAI API Key` 有没有问题，有可能是 Key 被 ban 了，或者再换个 IP 试试

**Comment by freer123** [comment]
换了新的key和ip也不行。

**Comment by erbanku** [comment]
> 换了新的key和ip也不行。

@freer123 Telegram 联系我吧，帮你看看，issue效率有点低，t.me/erbanku.com

**Comment by freer123** [comment]
果然是api key被封了，换了一个账号就行了，谢谢你们，speechgpt现在非常好用! 希望能够以后升级到GPT3.5.

**Comment by erbanku** [comment]
> 果然是api key被封了，换了一个账号就行了，谢谢你们，speechgpt现在非常好用! 希望能够以后升级到GPT3.5.

现在就是 `GPT-3.5` 吧？

**Comment by hahahumble** [comment]
> > 果然是 api key 被封了，换了一个账号就行了，谢谢你们，speechgpt 现在非常好用！希望能够以后升级到 GPT3.5.
> 
> 现在就是 `GPT-3.5` 吧？

是的
