### ISSUE TITLE
输入法键盘挡住

### ISSUE THREAD

**Issue by freer123** [hahahumble/speechgpt#12]
### Is your feature request related to a problem?

在手机上使用speechgpt时，每次点record或输入文字时，输入法键盘都会跳出挡住文本框和record键，这样无法看见输入的文字，很难修改文字，不知有没有好的解决方法。小米手机上似乎没有设置可以解决这个问题。

### Describe the solution you'd like

重新调整UI使得输入法键盘不会挡住文本框和record键。

**Comment by hahahumble** [comment]
<img width="200" alt="samsung-s23" src="https://user-images.githubusercontent.com/81009071/229293732-0bbab2a2-4ef9-4829-bb37-769a01e8f73e.png">
有截图吗，我这测试是没有问题的

**Comment by freer123** [comment]
![Uploading 微信图片_20230401220954.jpg…]()

**Comment by freer123** [comment]
![微信图片_20230401220954](https://user-images.githubusercontent.com/129358049/229294465-5516bebb-b396-4370-8d36-6f70b65281a5.jpg)

**Comment by hahahumble** [comment]
换个输入法或者浏览器试试，我在多台设备上测试没发现问题

**Comment by freer123** [comment]
已解决，讯飞输入法和搜狗输入法会被挡，只有百度输入法没问题。谢谢。
