### ISSUE TITLE
安装报错，package.json是否缺少tippy.js依赖？

### ISSUE THREAD

**Issue by arange** [hahahumble/speechgpt#2]
我用的是pnpm不是yarn，但是应该是一回事，似乎在dependencies里缺少了tippy.js
我自己install之后就解决了

**Comment by hahahumble** [comment]
这是 `tippy.js` 版本的问题，之后修复

**Comment by hahahumble** [comment]
`tippy.js` 的错误修复了，谢谢你的反馈
