### ISSUE TITLE
希望加入语音重听功能

### ISSUE THREAD

**Issue by XMZOVO** [hahahumble/speechgpt#28]
### Is your feature request related to a problem?

毕竟联系口语的初学者，很难一次听清😘

### Describe the solution you'd like

在对话的内容加上重播按钮

**Comment by XMZOVO** [comment]
目前这个对话后面按钮会有些阻挡划词复制
<img width="202" alt="image" src="https://user-images.githubusercontent.com/11494827/229704456-4c2571cd-6d78-4e1c-acfb-69b50eae4c84.png">

**Comment by hahahumble** [comment]
> 目前这个对话后面按钮会有些阻挡划词复制
> <img width="202" alt="image" src="https://user-images.githubusercontent.com/11494827/229704456-4c2571cd-6d78-4e1c-acfb-69b50eae4c84.png">
> 

确实是有这个问题，有好的解决方案可以分享下

**Comment by XMZOVO** [comment]
> > 目前这个对话后面按钮会有些阻挡划词复制
> > <img alt="image" width="202" src="https://user-images.githubusercontent.com/11494827/229704456-4c2571cd-6d78-4e1c-acfb-69b50eae4c84.png">
> 
> 确实是有这个问题，有好的解决方案可以分享下

另外，是否该将回复也填入assistant role，以形成完整的上下文。
<img width="519" alt="image" src="https://user-images.githubusercontent.com/11494827/229976138-afeff7de-d8ff-40cc-9a71-f0ad94cbfe08.png">

**Comment by XMZOVO** [comment]
哦刚看到，设置里可以选择😃

**Comment by KaelInvoker** [comment]
老哥，在哪里可以设置重听啊？？我怎么没找到

**Comment by XMZOVO** [comment]
> 老哥，在哪里可以设置重听啊？？我怎么没找到

没有，我说的设置可以切换带gpt回复的上下文。
最近amazon的账号被停用了，不知道还有什么其他好用的语音合成api没有。
我感觉这个项目对我来说练习口语真是非常的有用，Thanks 😆@hahahumble

**Comment by hahahumble** [comment]
已经加上语音重听功能了

**Comment by hahahumble** [comment]
> 没有，我说的设置可以切换带 gpt 回复的上下文。 最近 amazon 的账号被停用了，不知道还有什么其他好用的语音合成 api 没有。 我感觉这个项目对我来说练习口语真是非常的有用，Thanks 😆@hahahumble

目前语音合成还支持 Azure 的 API，Azure 语音合成每个月有 50 万个字符免费，效果也很不错

**Comment by XMZOVO** [comment]
> > 目前这个对话后面按钮会有些阻挡划词复制
> > <img alt="image" width="202" src="https://user-images.githubusercontent.com/11494827/229704456-4c2571cd-6d78-4e1c-acfb-69b50eae4c84.png">
> 
> 确实是有这个问题，有好的解决方案可以分享下

感觉可以参考Github这里的按钮设计，在代码块按下并移动，复制按钮会自动隐藏。
```js
console.log("This is a very very very very very very very very very very very very long GitHub markdown block")
```
