### ISSUE TITLE
希望加上访问密码

### ISSUE THREAD

**Issue by wubin2** [hahahumble/speechgpt#36]
### Is your feature request related to a problem?

让系统更安全、控制token滥用

### Describe the solution you'd like

在环境变量中加入网站访问密码

**Comment by stevenlee87** [comment]
我也想提这个需求。不然现在网页要是被别人发现了，会消耗自己的token额度。

**Comment by erbanku** [comment]
You can deploy without providing any environment credentials and let the user bring their credentials when using the service. By the way, we are considering adding the password protection functionality soon. Please keep an eye on the project.
https://github.com/hahahumble/speechgpt/issues/44#issuecomment-1512848199

**Comment by hahahumble** [comment]
目前已经支持设置网页访问密码 (v0.4.1)
