### ISSUE TITLE
Fail to deploy with environment variables

### ISSUE THREAD

**Issue by TomBener** [hahahumble/speechgpt#37]
### Describe the bug

I have deployed the project on Vercel and set the corresponding keys. However, it prompted that `You don't have provided an OpenAI API Key`.

### Steps to reproduce

On Vercel's dashboard, I've set 4 keys as follows:

```
OPENAI_API_KEY: [my own key]
OPENAI_HOST: [my own address]
AZURE_REGION: eastus
AZURE_KEY: [my own key]
```

**Comment by hahahumble** [comment]
You need to set it like this:
```env
VITE_OPENAI_API_KEY:[my_own_key]
VITE_OPENAI_HOST:[my_own_address]
VITE_AZURE_REGION:eastus
VITE_AZURE_KEY:[my_own_key]
```
And we have also added a button in README to deploy directly to Vercel with environment variables

**Comment by TomBener** [comment]
Thanks! I've made it by clicking the button to deploy on Vercel. But it got stuck on "Waiting" all the time on the page with my own deployment. Please help me fix it.

<img width="702" alt="CleanShot 2023-04-07 at 08 07 03@2x" src="https://user-images.githubusercontent.com/49151155/230515177-1308b622-43d2-4ef3-8167-d371244bfceb.png">
