### ISSUE TITLE
SpeechRecognition经常报错

### ISSUE THREAD

**Issue by arange** [hahahumble/speechgpt#4]
第一次Record是ok的，大概2～3次之后就开始报错了
我猜测是不能无限次new SpeechRecognition()，应该是chrome的限制
我把第一次new的instance放到state里，之后每次都用同一个就解决了，不过我没法新建branch提PR所以麻烦作者亲自修复了

**Comment by arange** [comment]
使用的是System，不是Azure

**Comment by hahahumble** [comment]
非常感谢你的反馈，这个问题现在已经解决了
