### ISSUE TITLE
设置了openai api key 但提示未提供

### ISSUE THREAD

**Issue by xingfanxia** [hahahumble/speechgpt#47]
### Describe the bug

![image](https://user-images.githubusercontent.com/8936233/230844308-9919b455-c18c-4663-a1ec-98ef70c366f7.png)
设置里显示已经设定
![image](https://user-images.githubusercontent.com/8936233/230844434-ccf2658b-78dc-4379-a848-f1a76eec187e.png)

### Steps to reproduce

在vercel部署并提供了environment vars
![image](https://user-images.githubusercontent.com/8936233/230845609-11388de2-fcf5-4d8b-886b-863a45566ab5.png)

**Comment by hahahumble** [comment]
Bug 已经修复
