### ISSUE TITLE
有没有人有Azure key可以借用一下

### ISSUE THREAD

**Issue by good1uck** [hahahumble/speechgpt#55]
### Is your feature request related to a problem?

有没有人有Azure key可以借用一下

### Describe the solution you'd like

有没有人有Azure key可以借用一下

**Comment by erbanku** [comment]
You can easily register an Azure account, then generate a free Azure key to get up to `5 million characters free per month` TTS quota for free.

Sharing the Azure key publicly is not recommended as it may cause some problems.

## Credit:
[Cognitive Speech Services Pricing | Microsoft Azure](https://azure.microsoft.com/en-us/pricing/details/cognitive-services/speech-services/)

| Instance                                                     | Category                                                     | Features | Price                               |
| ------------------------------------------------------------ | ------------------------------------------------------------ | -------- | ----------------------------------- |
| Free - Web/Container 1 concurrent request                    | Text to Speech                                               | Standard | 5 million characters free per month |
| Custom                                                       | 5 million characters free per month Endpoint hosting: 1 model free per month |          |                                     |
| Standard - Web/Container 100 concurrent requests for Base model 20 concurrent requests for Custom model | Text to Speech                                               | Standard | $4 per 1M characters                |
| Custom                                                       | $6 per 1M characters Endpoint hosting: $0.0537 per model per hour |          |                                     |
