### ISSUE TITLE
How to fill in the parameter when using vercel deployment?

### ISSUE THREAD

**Issue by stevenlee87** [hahahumble/speechgpt#57]
### Is your feature request related to a problem?

How to fill in the parameters for deploying services on vercel

### Describe the solution you'd like

I don't have any except the VITE_OPENAI_API_KEY parameter

![image](https://user-images.githubusercontent.com/4190121/232371103-e120936f-ea35-407d-a279-ffb596815a26.png)

**Comment by erbanku** [comment]
You only need to provide the `VITE_OPENAI_API_KEY` to deploy the service (or provide neither). 
OpenAI Host: to access directly if your network environment cannot access `api.openai.com` due to the government's firewall.
Azure related keys: To use Azure TTS and speech recognition services

**Comment by erbanku** [comment]
To deploy the service on Vercel, you only need to supply the `VITE_OPENAI_API_KEY` (or provide neither).
The OpenAI Host is for direct access if your network environment is unable to connect to `api.openai.com` due to government-imposed firewalls. 
Azure-related keys are required for utilizing Azure TTS and speech recognition services, while AWS-related keys are necessary for using the Amazon Polly TTS service.

**Comment by stevenlee87** [comment]
> To deploy the service on Vercel, you only need to supply the `VITE_OPENAI_API_KEY` (or provide none of these when deploying and fill it in after deploying in website settings.). The OpenAI Host is for direct access if your network environment is unable to connect to `api.openai.com` due to government-imposed firewalls. Azure-related keys are required for utilizing Azure TTS and speech recognition services, while AWS-related keys are necessary for using the Amazon Polly TTS service.

thank you for your answer.

The deploy button cannot be clicked if nothing is filled in during deployment. The message "missing" will be displayed
![image](https://user-images.githubusercontent.com/4190121/232658466-f094d9dc-4da3-4bd3-a0aa-56b981553d5d.png)

And then I filled in some random parameters, then deployed them, and didn't automatically reply to me. I wonder why
![image](https://user-images.githubusercontent.com/4190121/232456642-ac80e2ff-8c55-4f91-aa39-33265a9e7fd2.png)

**Comment by erbanku** [comment]
Please try this
### Deploying with Vercel
[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fhahahumble%2Fspeechgpt&env=VITE_OPENAI_API_KEY&envDescription=If%20you%20do%20not%20want%20to%20provide%20a%20value%2C%20use%20REPLACE_WITH_YOUR_OWN.&project-name=speechgpt&repository-name=speechgpt)

**Comment by stevenlee87** [comment]
> Please try this
> 
> ### Deploying with Vercel
> [![Deploy with Vercel](https://camo.githubusercontent.com/5e471e99e8e022cf454693e38ec843036ec6301e27ee1e1fa10325b1cb720584/68747470733a2f2f76657263656c2e636f6d2f627574746f6e)](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fhahahumble%2Fspeechgpt&env=VITE_OPENAI_API_KEY&envDescription=If%20you%20do%20not%20want%20to%20provide%20a%20value%2C%20use%20REPLACE_WITH_YOUR_OWN.&project-name=speechgpt&repository-name=speechgpt)
> 
> In this case you only need to provide the OpenAI API key when deploying ![image](https://user-images.githubusercontent.com/79493862/232661362-704328d6-e564-46b3-b864-5a52238cb597.png)

@erbanku thank you very much! this vercel deploy is good.

Why is this project's vercel deploy faulty? (https://github.com/hahahumble/speechgpt )

**Comment by erbanku** [comment]
Actually, the Vercel Deploy button is a link like the ones below.

Project's Vercel deploy button:
```
https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fhahahumble%2Fspeechgpt&env=VITE_OPENAI_API_KEY,VITE_OPENAI_HOST,VITE_AWS_REGION,VITE_AWS_ACCESS_KEY_ID,VITE_AWS_ACCESS_KEY,VITE_AZURE_REGION,VITE_AZURE_KEY&envDescription=If%20you%20do%20not%20want%20to%20provide%20a%20value%2C%20use%20REPLACE_WITH_YOUR_OWN.&project-name=speechgpt&repository-name=speechgpt
```
Modified Vercel deploy button:
```
https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fhahahumble%2Fspeechgpt&env=VITE_OPENAI_API_KEY&envDescription=If%20you%20do%20not%20want%20to%20provide%20a%20value%2C%20use%20REPLACE_WITH_YOUR_OWN.&project-name=speechgpt&repository-name=speechgpt
```
Ass you can see the original one requires other environment variables, and it's `must`, not `optional`, you can bypass this by deleting the other required environment variables in the link.

**Comment by stevenlee87** [comment]
@erbanku ok. I get it. Thank you again!
