### ISSUE TITLE
Can you add an access password feature?

### ISSUE THREAD

**Issue by stevenlee87** [hahahumble/speechgpt#61]
### Is your feature request related to a problem?

I hope you can set the access password, otherwise the token amount will be easily consumed once the page is discovered.

### Describe the solution you'd like

I hope you can set the access password, otherwise the token amount will be easily consumed once the page is discovered.

**Comment by hahahumble** [comment]
This feature will be added in later updates

**Comment by stevenlee87** [comment]
@hahahumble 

Could you tell me approximately what time it is, please?

**Comment by hahahumble** [comment]
Setting access code is now supported in this update (v0.4.1).
