### ISSUE TITLE
为啥不能用？

### ISSUE THREAD

**Issue by SamOct** [hahahumble/speechgpt#7]
填了key，但不能用。

**Comment by erbanku** [comment]
> 填了key，但不能用。
如果确定 key 没有问题的话，请确保你的网络环境能正常连接 `api.openai.com`。

**Comment by TomBener** [comment]
> 如果确定 key 没有问题的话，请确保你的网络环境能正常连接 `api.openai.com`

我也遇到了同样的情况，麻烦增加通过环境变量自定义 OpenAI API URL 的功能。

**Comment by erbanku** [comment]
> > 如果确定 key 没有问题的话，请确保你的网络环境能正常连接 `api.openai.com`
> 
> 我也遇到了同样的情况，麻烦增加通过环境变量自定义 OpenAI API URL 的功能。
> 
> 

如果是自行部署的话可以直接把，`api.openai.com` 替换为`openai-api-proxy.erbanku.com`来解决，后面会通过Cloudflare中转，绕过防火墙。

直接搜索替换即可，一步就能完成。

**Comment by SamOct** [comment]
搞定了，非常感谢！
