### ISSUE TITLE
可以提供docker版本吗

### ISSUE THREAD

**Issue by 9E307** [hahahumble/speechgpt#8]
### Is your feature request related to a problem?

请问可以做一个docker版本提供使用吗

### Describe the solution you'd like

需要docker版本方便部署。

**Comment by erbanku** [comment]
请问是有什么特殊需求吗？

直接用Vercel, Netlify, Cloudflare Pages这些已经很方便了呀。

**Comment by sparkssssssss** [comment]
附议
希望百忙之中做一个docker版本,我还是喜欢放到自己的vps上,稳定,可控
